### ISSUE TITLE
On Compact Mode, Rose Pine accent color doesn't affect the tab sidebar

### ISSUE THREAD

**Issue by KiKaraage** [feco/zen-rose-pine-dawn#1]
Compact mode
![image](https://github.com/user-attachments/assets/904b6ff9-3613-4d5a-b257-6e3c931e98e2)

Non compact mode for comparison
![image](https://github.com/user-attachments/assets/0eb19331-a489-4ca3-9b27-9f6a3a024bdf)

**Comment by RoMinjun** [comment]
That's controlled by `--zen-colors-tertiary`

I've made this for myself for the Rose Piné Theme (main)
```css
@-moz-document url-prefix("chrome:") {
      :root {
            --zen-colors-primary: #191724 !important;
            --zen-colors-secondary: #1f1d2e !important;
            --zen-colors-tertiary: #26233a !important;
            --zen-colors-border: #524f67 !important;
            --zen-dialog-background: #26233a !important;
            --toolbar-field-background-color: #191724 !important;
            --toolbar-field-focus-background-color: #191724 !important;
      }
}
```

Change the colors to your liking
